# Generated by Django 4.2.1 on 2023-06-04 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_cake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=5)),
                ('cooker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка кондитера',
                'verbose_name_plural': 'Оценки кондитеров',
            },
        ),
    ]
