# Generated by Django 4.2.1 on 2023-06-06 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_cake', '0002_cookerrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image_post', models.ImageField(upload_to='post_pics')),
                ('video_url', models.URLField(blank=True, help_text='URL видео', verbose_name='URL видео')),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Черновик'), ('2', 'Опубликовано'), ('3', 'На модерации')], default='1', max_length=1)),
                ('cooker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['id'],
            },
        ),
    ]
