# Generated by Django 4.2.1 on 2023-06-10 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_cake', '0005_product_filling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на видеорецепт (YouTube)', null=True, verbose_name='Ссылка на видео')),
                ('doc_recipe', models.FileField(blank=True, null=True, upload_to='recipe_doc/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image_recipe', models.ImageField(default='default_recipe.jpg', upload_to='recipe_pics')),
                ('status', models.CharField(choices=[('1', 'Черновик'), ('2', 'Опубликовано'), ('3', 'На модерации')], default='1', max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_cake.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_cake.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
