# Generated by Django 4.2.1 on 2023-06-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cake', '0008_alter_basket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
