# Generated by Django 4.2.1 on 2023-06-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cake', '0009_alter_basket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='video_url',
            field=models.CharField(blank=True, help_text='Ссылка на видеорецепт (YouTube)', max_length=400, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
